"""replace local auth with cognito

Revision ID: ecfa77771e82
Revises: ca816a0331aa
Create Date: 2026-08-29 14:01:57.761097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfa77771e82'
down_revision = 'ca816a0331aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Local-auth users have no cognito_sub and can no longer authenticate
    # once login moves to Cognito, so they can't be migrated in place.
    op.execute("DELETE FROM users WHERE cognito_sub IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
